site_name: BX4PIE
site_description: 'An Opensource controller for your DIY robots'
site_author: 'Rishikesavan Ramesh'
docs_dir: docs/
repo_name: 'rishikesavanramesh/bx4pie'
repo_url: 'https://github.com/RishikesavanRamesh/bx4pie/'
nav:
    - Home: index.md
theme:
  name: 'material'
