site_name: BX4PIE
site_description: 'An Opensource controller for your DIY robots'
site_author: 'Rishikesavan Ramesh'
repo_name: 'rishikesavanramesh/bx4pie'
repo_url: 'https://github.com/RishikesavanRamesh/bx4pie/'
docs_dir: docs/
nav:
    - Home: index.md
theme:
  name: 'rtd-dropdown'
extra_css:
  - docs/style.scss