site_name: BX4PIE
site_description: 'An Opensource controller for your DIY robots'
site_author: 'Rishikesavan Ramesh'
repo_name: 'rishikesavanramesh/bx4pie'
repo_url: 'https://github.com/RishikesavanRamesh/bx4pie/'
docs_dir: docs/
nav:
    - Home: index.md
theme: 
    name: spacelab


repo_url: https://github.com/cjsheets/readthedocs-dropdown

nav:
    - MkDocs: index.md
    - User Guide:
        - Writing Your Docs: index.md
        - Styling Your Docs: index.md
        - Configuration: index.md
        - Deploying Your Docs: index.md
        - Custom Themes: index.md
        - Plugins: index.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

extra_css:
    - styles.css

plugins:
    - search
